---
title: "Fire-Ants-Scrum"
author: "Jason Battles"
date: "October 4, 2018"
output:
  ioslides_presentation:
    highlight: espresso
    logo: images/FA-LogoPack/fireants-md-logo.jpg
    widescreen: yes
  beamer_presentation:
    highlight: espresso
  slidy_presentation:
    highlight: espresso
---

## Items in Flight
* **Pivotal Labs Engagement** - POSTPONED!!!
* Now attempting to target new dates.  pls confirm.
    - Option 1 06-08NOV 
    - Option 2 12-14NOV (better for Bee in CHI, MON-WED instead)
* Deploying R on PAS
    
## **Many Hands = Light Work**
* Update your microservice issues in GitHub
* Schedule your preparatory pair programming
    
## Around the Horn (a.k.a. Discoveries this week)

* **Cohen** - learning R on PAS
* **Mordi** - Grace Hopper Conference. developing lite applications to meet lower hw specs in emerging markets. data anonyminity. 
* **Goyette** - SitRep report for Navigators. Investigating new models
* **Sabarese** - underscored Cloudera and Hortonworks merger.  keras.
* **Battles** - concourse tutorial, PitchRx 1.8.4, package "vendoring", interactive R in Containers, DataRobot
* **Nixon** - working with new mobile dev packages
* **Sweezy** - fighting flu-bug.  consolidating API.

## Summary Notes
                  
*    
                                
