---
title: "Fire-Ants-Scrum"
author: "Jason Battles"
date: "February 1, 2018"
output:
  ioslides_presentation:
    highlight: espresso
    logo: images/FA-LogoPack/fireants-md-logo.jpg
    widescreen: yes
  beamer_presentation:
    highlight: espresso
  slidy_presentation:
    highlight: espresso
---

## Items in Flight
* Bat / Sweers to upload PF.  Errors remain
* Bee updating App Flow diagram. 
* Bat not advancing with Kurt's nomination.  
* Sweers working on Fire Ants blog.  All team members contribute content
* Nix working to pull ML guidance from API
* Bat has some movement on EMC Dojo

## Funshop Objectives
1. Prepare for EMC Dojo
2. Add ML to mobile app
3. Document issues in GitHub
 
## Funshop Format - 06FEB
1. Get organized.  Dust off the cobwebs (Bat)
2. Application Flow (Mordi)
3. Module Review: mlb-analytics-ant (Bat, Cohen)
4. Module Review: mlb-machine-learning (Goyette, Mordi)
5. Pair Programming via WebEx (if time remains)
    - mlb-analytics-ant
    - mlb-mobile
    - mlb-machine-learning
 
## Funshop Format - 07FEB
1. Module Review: mlb-datafresh (Cohen, Bat)
2. Module Review: mlb-mobile-app (Nixon, Sweers)
3. Pair Programming via WebEx
    - PKS platform config?
    - mlb-mobile
    - mlb-machine-learning

## Funshop Format - 08FEB
1. Module Review: mlb-api (Sweers)
2. Module Review: PAS/PKS platform (Sabarese)
3. Pair Programming via WebEx
    - PAS/PKS platform config?
    - mlb-mobile
    - mlb-analytics-ant

## Administrivia
* 2018 Scrum Schedule - invitations updated.
* LinkedIn - https://www.linkedin.com/company/the-fire-ants/
* Upcoming Fire Ants Workshops
    - **06-08FEB** - Virtual Funshop
    - **Spring** - TBD: EMC Dojo.
    - **06-08JUN?** - Chicago 
    - **SEP NYC?** - Pivotal office? Kenny to inquire.
    
## Around the Horn (a.k.a. Discoveries this week)

* **Cohen** - Kenny is awesome. PKCS / PAS. Working on project to improve process flow and output from RVtools and VNX config summaries.  Panda libraries for Python.
* **Sweezy** - closer inspection of mlb-api. playing with geospatial queries.
* **Nixon** - Kenny is awesome. PKCS / PAS.
* **Mordi** - K.I.S.S. with customers.
* **Goyette** - formal Machine Learning.  Building knn models (Nearest Neighbor).
* **Sabarese** - PKS / PCF / PAS
* **Battles** - MLBAM blocking access to 2017. PKS/PAS.  

## Summary Notes
                    
                                
