---
title: "Data Dictionary - MLB Pitcher's Friend"
author: "Jason Battles"
date: "July 20, 2016"
output: html_document
---

## Description
This is a description of all the observation types that MLB Pitchers Friend application needs to compute the data analytics and prepare the visualizations.  These variables are available from MLB Pitch F/X system.  This data is extracted from the **inning_all.xml** file from this repository http://gd2.mlb.com/components/game/mlb/

This is for non-commercial, MLB / Data Analytics enthusiasts.

-------------------------------------------------------------
Variable        Description                                                 
-------------   ----------------------------------------------------------------        
des             Description of pitch outcome. **Example Data** "Called Strike" "Ball" "Swinging Strike" "Ball" ...

id              UNK   **Example Data** - 3 4 5 6 7 8 13 14 15 16 ...

type            pitch outcome.  **Example Data** -  "S" "B" "S" "B" ...

tfs             UNK   **Example Data** -  "170906" "170922" "170936" "170953" ...

tfs_zulu        UNK  **Example Data** -  "2016-07-02T17:09:06Z" "2016-07-02T17:09:22Z" "2016-07-02T17:09:36Z" "2016-07-02T17:09:53Z" ...

x               UNK **Example Data** - 117 79.3 93 96 67.3 ...
 
y               UNK **Example Data** - 171 216 237 227 207 ...
 
event_num       UNK **Example Data** -  "3" "4" "5" "6" ...
 
sv_id           a date/time stamp of when the PITCHf/x tracking system first detected the pitch in the air, it is in the format YYMMDD_hhmmss.  **Example Data** -  "160702_131114" "160702_131128" "160702_131141" "160702_131200" ...
 
play_guid       UNK **Example Data** -  "738f6446-3ba5-4989-8514-f1ebe93c16a2" "ed9a82bb-91b9-485f-b24d-0006910bff72" "ae076906-5d34-4a03-ac83-6b2572796d34" "c9bf731e-323f-4b9a-99f0-3c0113f8e4c8" ...
 
start_speed     the pitch speed, in miles per hour and in three dimensions, measured at the initial point, y0. Of the two speeds, this one is closer to the speed measured by a radar gun and what we are familiar with for a pitcher’s “velocity” **Example Data** - 83.7 81.1 72.6 74.3 86.7 86.2 84.2 74.6 84.7 83.8 ...
 
end_speed       the pitch speed measured as it crossed the front of home plate.**Example Data** - 74.4 74.2 66.2 67.8 80.1 79.2 76.4 67.7 77.7 76.5 ...
 
sz_top          the distance in feet from the ground to the top of the current batter’s rulebook strike zone as measured from the video by the PITCHf/x operator. The operator sets a line at the batter’s belt as he settles into the hitting position, and the PITCHf/x software adds four inches up for the top of the zone.**Example Data** - 3.47 3.47 3.47 3.47 3.47 3.47 3.26 3.26 3.26 3.26 ...
 
sz_bot          the distance in feet from the ground to the bottom of the current batter’s rulebook strike zone. The PITCHf/x operator sets a line at the hollow of the knee for the bottom of the zone.**Example Data** - 1.5 1.5 1.5 1.5 1.5 1.5 1.48 1.48 1.48 1.48 ...
 
pfx_x           the horizontal movement, in inches, of the pitch between the release point and home plate, as compared to a theoretical pitch thrown at the same speed with no spin-induced movement. This parameter is measured at y=40 feet regardless of the y0 value. **Example Data** - -5 -0.01 6.43 -6.6 -2.94 -2.33 -2.66 -9.81 -3.71 -4.02 ...
 
pfx_z           the vertical movement, in inches, of the pitch between the release point and home plate, as compared to a theoretical pitch thrown at the same speed with no spin-induced movement. This parameter is measured at y=40 feet regardless of the y0 value. **Example Data** - 15.46 6.8 -7.11 13.47 12.63 ...
 
px              the left/right distance, in feet, of the pitch from the middle of the plate as it crossed home plate. The PITCHf/x coordinate system is oriented to the catcher’s/umpire’s perspective, with distances to the right being positive and to the left being negative. **Example Data** - 0.046 1.035 0.678 0.599 1.35 ...
 
pz              the height of the pitch in feet as it crossed the front of home plate. **Example Data** - 2.552 0.896 0.128 0.485 1.235 ...
 
x0              the left/right distance, in feet, of the pitch, measured at the initial point. **Example Data** - -0.935 -1.064 -1.289 -1.011 -0.901 ...
 
y0              the distance in feet from home plate where the PITCHf/x system is set to measure the initial parameters. This parameter has been variously set at 40, 50, or 55 feet (and in a few instances 45 feet) from the plate at different times throughout the 2007 season as Sportvision experiments with optimal settings for the PITCHf/x measurements. Sportvision settled on 50 feet in the second half of 2007, and this value of y0=50 feet has been used since. Changes in this parameter impact the values of all other parameters measured at the release point, such as start_speed. **Example Data** - 50 50 50 50 50 50 50 50 50 50 ...
 
z0              the height, in feet, of the pitch, measured at the initial point. **Example Data** - 6.49 6.42 6.54 6.37 6.34 ...
 
vx0                 the velocity of the pitch, in feet per second, in three dimensions, measured at the initial point. **Example Data** - 3.87 4.88 2.35 5.24 6.58 ...
 
vy0             the velocity of the pitch, in feet per second, in three dimensions, measured at the initial point. **Example Data** - -122 -119 -106 -109 -127 ...
 
vz0             the velocity of the pitch, in feet per second, in three dimensions, measured at the initial point.**Example Data** - -7.36 -7.98 -3.56 -8.67 -10.45 ...
 
ax              the acceleration of the pitch, in feet per second per second, in three dimensions, measured at the initial point. **Example Data** - -7.299 -0.014 7.059 -7.728 -4.768 ...
 
ay              the acceleration of the pitch, in feet per second per second, in three dimensions, measured at the initial point. **Example Data** - 33 26.3 25.3 22.3 25.4 ...
 
az              the acceleration of the pitch, in feet per second per second, in three dimensions, measured at the initial point. **Example Data** - -9.55 -22.59 -39.91 -16.34 -11.58 ...
 
break_y         the distance in feet from home plate to the point in the pitch trajectory where the pitch achieved its greatest deviation from the straight line path between the release point and the front of home plate. **Example Data** -  "23.6" "23.8" "23.7" "23.7" ...
 
break_angle     the angle, in degrees, from vertical to the straight line path from the release point to where the pitch crossed the front of home plate, as seen from the catcher’s/umpire’s perspective. **Example Data** -  "28.6" "-2.2" "-10.4" "20.5" ...
 
break_length    the measurement of the greatest distance, in inches, between the trajectory of the pitch at any point between the release point and the front of home plate, and the straight line path from the release point and the front of home plate, per the MLB Gameday team. John Walsh’s article “In Search of the Sinker” has a good illustration of this parameter.**Example Data** -  "3.7" "7.1" "15.4" "6.7" ...
 
pitch_type      the most probable pitch type according to a neural net classification algorithm developed by Ross Paul of MLBAM. **Example Data** -  "CH" "CH" "FF" "CH" ...
 
type_confidence     the value of the weight at the classification algorithm’s output node corresponding to the most probable pitch type, this value is multiplied by a factor of 1.5 if the pitch is known by MLBAM to be part of the pitcher’s repertoire.**Example Data** - 0.75 0.868 0.902 0.898 0.945 0.927 0.75 0.907 0.912 0.75 ...

zone                UNK **Example Data** - 5 14 14 14 14 5 11 13 13 11 ...
 
nasty               UNK **Example Data** - 41 45 33 35 40 20 56 46 23 48 ...
 
spin_dir            UNK **Example Data** - 197.9 180.1 42.4 206 193 ...
 
spin_rate           UNK **Example Data** - 2817 1173 1429 2355 2424 ...
 
cc                  UNK **Example Data** -  "" "" "" "" ...
 
mt                  UNK **Example Data** -  "" "" "" "" ...
 
url                 Link to the source file. **Example Data** -  "http://gd2.mlb.com/components/game/mlb/year_2016/month_07/day_02/gid_2016_07_02_clemlb_tormlb_1/inning/inning_all.xml" "http://gd2.mlb.com/components/game/mlb/year_2016/month_07/day_02/gid_2016_07_02_clemlb_tormlb_1/inning/inning_all.xml" "http://gd2.mlb.com/components/game/mlb/year_2016/month_07/day_02/gid_2016_07_02_clemlb_tormlb_1/inning/inning_all.xml" "http://gd2.mlb.com/components/game/mlb/year_2016/month_07/day_02/gid_2016_07_02_clemlb_tormlb_1/inning/inning_all.xml" ...
 
inning_side         top or bottom of the inning **Example Data** -  "top" "top" "top" "top" ...
 
inning              inning number **Example Data** - 1 1 1 1 1 1 1 1 1 1 ...
 
next_                   UNK **Example Data** -  "Y" "Y" "Y" "Y" ...
 
num                 UNK **Example Data** - 1 1 1 1 1 1 2 2 2 2 ...
 
on_1b               Batter ID of runner on 1st Base **Example Data** - NA NA NA NA NA NA NA NA NA NA ...
 
on_2b               Batter ID of runner on 2nd Base **Example Data** - NA NA NA NA NA NA NA NA NA NA ...
 
on_3b               Batter ID of runner on 1st Base **Example Data** - NA NA NA NA NA NA NA NA NA NA ...
 
gameday_link        UNK **Example Data** -  "gid_2016_07_02_clemlb_tormlb_1" "gid_2016_07_02_clemlb_tormlb_1" "gid_2016_07_02_clemlb_tormlb_1" "gid_2016_07_02_clemlb_tormlb_1" ...

 count              Ball-Strike count at time of pitch. Factor w/ 12 levels **Example Data** - ""0-0","0-1","0-2",..: 1 2 5 6 9 12 1 4 7 10 ...
 
 
pitcher             Pitcher ID **Example Data** - 462136 462136 462136 462136 462136 ...

batter              Batter ID.  At the plate. **Example Data** - 434658 434658 435063 435063 434658 ...

num                 UNK **Example Data** - 1 40 29 4 21 22 2 38 39 23 ...

b                   Count of Balls when At Bat ended.  **Example Data** - 3 2 0 2 3 1 3 2 3 3 ...

s                   Count of Balls when At Bat ended.  **Example Data** - 2 2 3 3 2 3 3 2 2 2 ...

o                   Count of Balls when At Bat ended.   **Example Data** - 0 3 1 3 1 2 1 1 2 3 ...

start_tfs           Timestamp **Example Data** -   "170851" "183859" "181608" "171409" ...

start_tfs_zulu      Timestamp. Zulu time. **Example Data** -   "2016-07-02T17:08:51Z" "2016-07-02T18:38:59Z" "2016-07-02T18:16:08Z" "2016-07-02T17:14:09Z" ...

stand               Batter hitting Left or Right. **Example Data** -   "R" "R" "R" "R" ...

b_height            Batter Height **Example Data** -   "5-10" "5-10" "6-1" "6-1" ...

p_throws            Pitcher throws Left or Right **Example Data** -   "R" "R" "R" "R" ...

atbat_des           Description of final outcome of At Bat **Example Data** -   "Rajai Davis homers (9) on a line drive to left field.  " "Rajai Davis grounds out, shortstop Troy Tulowitzki to first baseman Edwin Encarnacion.  " "Mike Napoli strikes out swinging.  " "Mike Napoli strikes out swinging.  " ...

event_num           UNK **Example Data** - "11" "339" "252" "39" ...

event               Final outcome of At Bat **Example Data** -   "Home Run" "Groundout" "Strikeout" "Strikeout" ...

score               Score at time of At Bat **Example Data** -   "T" NA NA NA ...

home_team           Home team code **Example Data** - "TEX" "ANA" "CLE" ...

home_team_runs      Home team score at time of At Bat **Example Data** -   "0" "3" "3" "0" ...

away_team           Home team code **Example Data** - "TEX" "ANA" "CLE" ...

away_team_runs      Away team score at time of At Bat **Example Data** -   "1" "3" "2" "1" ...

next_               UNK **Example Data** -   "Y" "Y" "Y" "Y" ...

event2              UNK **Example Data** -   NA NA NA NA ...

event2_es           UNK **Example Data** -   NA NA NA NA ...

batter_name         Batter Name **Example Data** - "Rajai Davis" "Rajai Davis" "Mike Napoli" "Mike Napoli" ...

pitcher_name        Pitcher Name **Example Data** - "Marco Estrada" "Marco Estrada" "Marco Estrada" "Marco Estrada" ...

deck                Batter on deck (next up)

hole                Batter in the hole (batter 3rd in line)

ind                 UNK

next                UNK
 -------------------------------------------------------------
 
